# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idea.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_partidea(object):
    def setupUi(self, partidea):
        partidea.setObjectName("partidea")
        partidea.resize(557, 486)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        partidea.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/input_tablet_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        partidea.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(partidea)
        self.label.setGeometry(QtCore.QRect(120, 51, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_tec_part = QtWidgets.QTextEdit(partidea)
        self.txt_tec_part.setGeometry(QtCore.QRect(210, 51, 321, 74))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.txt_tec_part.setFont(font)
        self.txt_tec_part.setObjectName("txt_tec_part")
        self.label_2 = QtWidgets.QLabel(partidea)
        self.label_2.setGeometry(QtCore.QRect(120, 131, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_pro_part = QtWidgets.QTextEdit(partidea)
        self.txt_pro_part.setGeometry(QtCore.QRect(210, 131, 321, 74))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.txt_pro_part.setFont(font)
        self.txt_pro_part.setObjectName("txt_pro_part")
        self.label_3 = QtWidgets.QLabel(partidea)
        self.label_3.setGeometry(QtCore.QRect(120, 211, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_qc_part = QtWidgets.QTextEdit(partidea)
        self.txt_qc_part.setGeometry(QtCore.QRect(210, 211, 321, 73))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.txt_qc_part.setFont(font)
        self.txt_qc_part.setObjectName("txt_qc_part")
        self.label_4 = QtWidgets.QLabel(partidea)
        self.label_4.setGeometry(QtCore.QRect(120, 290, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_tec_support = QtWidgets.QTextEdit(partidea)
        self.txt_tec_support.setGeometry(QtCore.QRect(210, 290, 321, 74))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.txt_tec_support.setFont(font)
        self.txt_tec_support.setObjectName("txt_tec_support")
        self.gpb_deal = QtWidgets.QGroupBox(partidea)
        self.gpb_deal.setGeometry(QtCore.QRect(10, 50, 91, 261))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.gpb_deal.setFont(font)
        self.gpb_deal.setObjectName("gpb_deal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gpb_deal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chk_devi_release = QtWidgets.QCheckBox(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chk_devi_release.setFont(font)
        self.chk_devi_release.setObjectName("chk_devi_release")
        self.verticalLayout.addWidget(self.chk_devi_release)
        self.chk_rework = QtWidgets.QCheckBox(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chk_rework.setFont(font)
        self.chk_rework.setObjectName("chk_rework")
        self.verticalLayout.addWidget(self.chk_rework)
        self.chk_downgrade = QtWidgets.QCheckBox(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chk_downgrade.setFont(font)
        self.chk_downgrade.setObjectName("chk_downgrade")
        self.verticalLayout.addWidget(self.chk_downgrade)
        self.chk_direc_sales = QtWidgets.QCheckBox(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chk_direc_sales.setFont(font)
        self.chk_direc_sales.setObjectName("chk_direc_sales")
        self.verticalLayout.addWidget(self.chk_direc_sales)
        self.chk_scrap = QtWidgets.QCheckBox(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.chk_scrap.setFont(font)
        self.chk_scrap.setObjectName("chk_scrap")
        self.verticalLayout.addWidget(self.chk_scrap)
        self.btn_deal_method = QtWidgets.QPushButton(self.gpb_deal)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btn_deal_method.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/pass_to_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_deal_method.setIcon(icon1)
        self.btn_deal_method.setObjectName("btn_deal_method")
        self.verticalLayout.addWidget(self.btn_deal_method)
        self.btn_save_idea = QtWidgets.QPushButton(partidea)
        self.btn_save_idea.setGeometry(QtCore.QRect(450, 440, 72, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_idea.sizePolicy().hasHeightForWidth())
        self.btn_save_idea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btn_save_idea.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Save_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_idea.setIcon(icon2)
        self.btn_save_idea.setObjectName("btn_save_idea")
        self.btn_sign_name = QtWidgets.QPushButton(partidea)
        self.btn_sign_name.setGeometry(QtCore.QRect(370, 440, 72, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sign_name.sizePolicy().hasHeightForWidth())
        self.btn_sign_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btn_sign_name.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/dealidea.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sign_name.setIcon(icon3)
        self.btn_sign_name.setObjectName("btn_sign_name")

        self.retranslateUi(partidea)
        QtCore.QMetaObject.connectSlotsByName(partidea)
        partidea.setTabOrder(self.txt_tec_part, self.txt_pro_part)
        partidea.setTabOrder(self.txt_pro_part, self.txt_qc_part)
        partidea.setTabOrder(self.txt_qc_part, self.txt_tec_support)
        partidea.setTabOrder(self.txt_tec_support, self.chk_devi_release)
        partidea.setTabOrder(self.chk_devi_release, self.chk_rework)
        partidea.setTabOrder(self.chk_rework, self.chk_downgrade)
        partidea.setTabOrder(self.chk_downgrade, self.chk_direc_sales)
        partidea.setTabOrder(self.chk_direc_sales, self.chk_scrap)
        partidea.setTabOrder(self.chk_scrap, self.btn_save_idea)
        partidea.setTabOrder(self.btn_save_idea, self.btn_sign_name)

    def retranslateUi(self, partidea):
        _translate = QtCore.QCoreApplication.translate
        partidea.setWindowTitle(_translate("partidea", "意见输入"))
        self.label.setText(_translate("partidea", "技术部意见"))
        self.txt_tec_part.setHtml(_translate("partidea", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("partidea", "工艺部意见"))
        self.label_3.setText(_translate("partidea", "质量部意见"))
        self.label_4.setText(_translate("partidea", "技术支持部意见"))
        self.gpb_deal.setTitle(_translate("partidea", "选择处置方式"))
        self.chk_devi_release.setText(_translate("partidea", "偏差放行"))
        self.chk_rework.setText(_translate("partidea", "返工"))
        self.chk_downgrade.setText(_translate("partidea", "降级"))
        self.chk_direc_sales.setText(_translate("partidea", "定向销售"))
        self.chk_scrap.setText(_translate("partidea", "报废"))
        self.btn_deal_method.setToolTip(_translate("partidea", "<html><head/><body><p><span style=\" font-style:italic; color:#55ff00;\">不在上述列表中的处置方式可手动输入</span></p></body></html>"))
        self.btn_deal_method.setText(_translate("partidea", "Add"))
        self.btn_save_idea.setText(_translate("partidea", "保存"))
        self.btn_sign_name.setToolTip(_translate("partidea", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic; color:#0055ff;\">在意见输入框末尾添加</span></p></body></html>"))
        self.btn_sign_name.setText(_translate("partidea", "签名"))


