# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qa_data.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QAData(object):
    def setupUi(self, QAData):
        QAData.setObjectName("QAData")
        QAData.resize(675, 479)
        self.centralwidget = QtWidgets.QWidget(QAData)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 1, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_4.setContentsMargins(9, 1, -1, -1)
        self.formLayout_4.setHorizontalSpacing(7)
        self.formLayout_4.setVerticalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.test_batch = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_batch.sizePolicy().hasHeightForWidth())
        self.test_batch.setSizePolicy(sizePolicy)
        self.test_batch.setObjectName("test_batch")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.test_batch)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.date_produce = QtWidgets.QDateEdit(self.groupBox)
        self.date_produce.setCalendarPopup(True)
        self.date_produce.setObjectName("date_produce")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.date_produce)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.date_test = QtWidgets.QDateEdit(self.groupBox)
        self.date_test.setCalendarPopup(True)
        self.date_test.setObjectName("date_test")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_test)
        self.horizontalLayout.addLayout(self.formLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setVerticalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.comb_test_coustomer = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comb_test_coustomer.sizePolicy().hasHeightForWidth())
        self.comb_test_coustomer.setSizePolicy(sizePolicy)
        self.comb_test_coustomer.setEditable(True)
        self.comb_test_coustomer.setObjectName("comb_test_coustomer")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comb_test_coustomer)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comb_pro_type = QtWidgets.QComboBox(self.groupBox)
        self.comb_pro_type.setEditable(True)
        self.comb_pro_type.setObjectName("comb_pro_type")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comb_pro_type)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comb_pro_color = QtWidgets.QComboBox(self.groupBox)
        self.comb_pro_color.setEditable(True)
        self.comb_pro_color.setObjectName("comb_pro_color")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comb_pro_color)
        self.horizontalLayout.addLayout(self.formLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(139, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_test_save = QtWidgets.QPushButton(self.frame_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Save_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_test_save.setIcon(icon)
        self.btn_test_save.setObjectName("btn_test_save")
        self.horizontalLayout_2.addWidget(self.btn_test_save)
        self.btn_test_clear = QtWidgets.QPushButton(self.frame_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/delete_file_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_test_clear.setIcon(icon1)
        self.btn_test_clear.setObjectName("btn_test_clear")
        self.horizontalLayout_2.addWidget(self.btn_test_clear)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_test_tounpass = QtWidgets.QPushButton(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_test_tounpass.setIcon(icon2)
        self.btn_test_tounpass.setObjectName("btn_test_tounpass")
        self.horizontalLayout_2.addWidget(self.btn_test_tounpass)
        spacerItem3 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.line_keyword = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_keyword.sizePolicy().hasHeightForWidth())
        self.line_keyword.setSizePolicy(sizePolicy)
        self.line_keyword.setObjectName("line_keyword")
        self.horizontalLayout_2.addWidget(self.line_keyword)
        self.btn_test_search = QtWidgets.QPushButton(self.frame_2)
        self.btn_test_search.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_test_search.setIcon(icon3)
        self.btn_test_search.setObjectName("btn_test_search")
        self.horizontalLayout_2.addWidget(self.btn_test_search)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_2)
        self.test_data_view = QtWidgets.QTableView(self.centralwidget)
        self.test_data_view.setObjectName("test_data_view")
        self.verticalLayout.addWidget(self.test_data_view)
        QAData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QAData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 23))
        self.menubar.setObjectName("menubar")
        QAData.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QAData)
        self.statusbar.setObjectName("statusbar")
        QAData.setStatusBar(self.statusbar)

        self.retranslateUi(QAData)
        QtCore.QMetaObject.connectSlotsByName(QAData)

    def retranslateUi(self, QAData):
        _translate = QtCore.QCoreApplication.translate
        QAData.setWindowTitle(_translate("QAData", "MainWindow"))
        self.groupBox.setTitle(_translate("QAData", "产品信息"))
        self.label.setText(_translate("QAData", "批号"))
        self.test_batch.setPlaceholderText(_translate("QAData", "复测则添加后缀-F1,-F2,..."))
        self.label_5.setText(_translate("QAData", "生产日期"))
        self.label_6.setText(_translate("QAData", "检验日期"))
        self.label_2.setText(_translate("QAData", "客户"))
        self.label_3.setText(_translate("QAData", "产品型号"))
        self.label_4.setText(_translate("QAData", "颜色"))
        self.btn_test_save.setText(_translate("QAData", "Save"))
        self.btn_test_clear.setText(_translate("QAData", "Clear"))
        self.btn_test_tounpass.setText(_translate("QAData", "登记为不合格品"))
        self.label_7.setText(_translate("QAData", "模糊查询"))
        self.line_keyword.setPlaceholderText(_translate("QAData", "批号或产品名称"))


