# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(537, 620)
        about.setMinimumSize(QtCore.QSize(537, 620))
        about.setMaximumSize(QtCore.QSize(537, 620))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        about.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(about)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(about)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 441, 16))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(about)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 351, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(about)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 441, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(about)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 411, 31))
        self.label_5.setMinimumSize(QtCore.QSize(411, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(about)
        self.label_6.setGeometry(QtCore.QRect(190, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icons/arrow_128px.ico"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(about)
        self.label_7.setGeometry(QtCore.QRect(190, 250, 41, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icons/arrow_128px.ico"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(about)
        self.label_8.setGeometry(QtCore.QRect(30, 290, 411, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(about)
        self.label_9.setGeometry(QtCore.QRect(30, 370, 411, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(about)
        self.label_10.setGeometry(QtCore.QRect(190, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("icons/arrow_128px.ico"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(about)
        self.label_11.setGeometry(QtCore.QRect(30, 450, 421, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(about)
        self.label_12.setGeometry(QtCore.QRect(190, 410, 41, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("icons/arrow_128px.ico"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(about)
        self.label_13.setGeometry(QtCore.QRect(30, 510, 351, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(about)
        self.label_14.setGeometry(QtCore.QRect(30, 540, 421, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(about)
        self.label_15.setGeometry(QtCore.QRect(30, 570, 481, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(about)
        self.label_16.setGeometry(QtCore.QRect(420, 10, 81, 81))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("icons/find.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Help"))
        self.label.setText(_translate("about", "功能介绍："))
        self.label_2.setText(_translate("about", "1、不良品目录 >> <录入检测数据> <登记不合格品>"))
        self.label_3.setText(_translate("about", "2、不良品处理:"))
        self.label_4.setText(_translate("about", "@ 责任部门主导分析填写 >> 原因分析，纠正措施，预防措施以及添加涉及到本次不良品改善的部门"))
        self.label_5.setText(_translate("about", "@ 意见职能部门 >> 提供对每单不合格品的处理意见"))
        self.label_8.setText(_translate("about", "@ 提交部门评审 >> 所有涉及到的部门评审不合格品处理"))
        self.label_9.setText(_translate("about", "@ 提交总经理评审 >> 总经理评审确认不合格品处理"))
        self.label_11.setText(_translate("about", "@ 处理跟踪 >> 按评审单处理每单不合格品并添加查询处置目录以便将来跟踪"))
        self.label_13.setText(_translate("about", "3、查询"))
        self.label_14.setText(_translate("about", "@ 处理跟踪 >> 提供所有的不合格品评审单的查询和打印"))
        self.label_15.setText(_translate("about", "@ 查询检测数据 >> 提供检测记录的查询,数据导出及生成可视化图表"))


