# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_unpass.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_unpass(object):
    def setupUi(self, new_unpass):
        new_unpass.setObjectName("new_unpass")
        new_unpass.resize(538, 315)
        new_unpass.setMinimumSize(QtCore.QSize(538, 315))
        new_unpass.setMaximumSize(QtCore.QSize(538, 315))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        new_unpass.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        new_unpass.setWindowIcon(icon)
        self.btn_clear = QtWidgets.QPushButton(new_unpass)
        self.btn_clear.setGeometry(QtCore.QRect(359, 270, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/delete_file_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear.setIcon(icon1)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_save_new_unpass = QtWidgets.QPushButton(new_unpass)
        self.btn_save_new_unpass.setGeometry(QtCore.QRect(440, 270, 75, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Save_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_new_unpass.setIcon(icon2)
        self.btn_save_new_unpass.setObjectName("btn_save_new_unpass")
        self.new_unpass_desc = QtWidgets.QTextEdit(new_unpass)
        self.new_unpass_desc.setGeometry(QtCore.QRect(89, 150, 431, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_unpass_desc.sizePolicy().hasHeightForWidth())
        self.new_unpass_desc.setSizePolicy(sizePolicy)
        self.new_unpass_desc.setObjectName("new_unpass_desc")
        self.label_8 = QtWidgets.QLabel(new_unpass)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 60, 16))
        self.label_8.setObjectName("label_8")
        self.splitter = QtWidgets.QSplitter(new_unpass)
        self.splitter.setGeometry(QtCore.QRect(89, 33, 181, 111))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.new_unpasstype = QtWidgets.QComboBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_unpasstype.sizePolicy().hasHeightForWidth())
        self.new_unpasstype.setSizePolicy(sizePolicy)
        self.new_unpasstype.setObjectName("new_unpasstype")
        self.new_batch = QtWidgets.QLineEdit(self.splitter)
        self.new_batch.setObjectName("new_batch")
        self.date_produce = QtWidgets.QDateEdit(self.splitter)
        self.date_produce.setCalendarPopup(True)
        self.date_produce.setObjectName("date_produce")
        self.new_unpass_qty = QtWidgets.QLineEdit(self.splitter)
        self.new_unpass_qty.setObjectName("new_unpass_qty")
        self.splitter_2 = QtWidgets.QSplitter(new_unpass)
        self.splitter_2.setGeometry(QtCore.QRect(20, 30, 61, 111))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.splitter_3 = QtWidgets.QSplitter(new_unpass)
        self.splitter_3.setGeometry(QtCore.QRect(360, 40, 161, 71))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.new_id = QtWidgets.QLabel(self.splitter_3)
        self.new_id.setText("")
        self.new_id.setObjectName("new_id")
        self.comb_new_coustom = QtWidgets.QComboBox(self.splitter_3)
        self.comb_new_coustom.setEditable(True)
        self.comb_new_coustom.setObjectName("comb_new_coustom")
        self.comb_new_unpassname = QtWidgets.QComboBox(self.splitter_3)
        self.comb_new_unpassname.setEditable(True)
        self.comb_new_unpassname.setObjectName("comb_new_unpassname")
        self.splitter_4 = QtWidgets.QSplitter(new_unpass)
        self.splitter_4.setGeometry(QtCore.QRect(290, 40, 61, 71))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_6 = QtWidgets.QLabel(self.splitter_4)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.splitter_4)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.splitter_4)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(new_unpass)
        QtCore.QMetaObject.connectSlotsByName(new_unpass)
        new_unpass.setTabOrder(self.new_unpasstype, self.new_batch)
        new_unpass.setTabOrder(self.new_batch, self.date_produce)
        new_unpass.setTabOrder(self.date_produce, self.new_unpass_qty)
        new_unpass.setTabOrder(self.new_unpass_qty, self.comb_new_coustom)
        new_unpass.setTabOrder(self.comb_new_coustom, self.comb_new_unpassname)
        new_unpass.setTabOrder(self.comb_new_unpassname, self.new_unpass_desc)
        new_unpass.setTabOrder(self.new_unpass_desc, self.btn_save_new_unpass)
        new_unpass.setTabOrder(self.btn_save_new_unpass, self.btn_clear)

    def retranslateUi(self, new_unpass):
        _translate = QtCore.QCoreApplication.translate
        new_unpass.setWindowTitle(_translate("new_unpass", "不合格品登记"))
        self.btn_clear.setText(_translate("new_unpass", "清空"))
        self.btn_save_new_unpass.setText(_translate("new_unpass", "保存"))
        self.new_unpass_desc.setPlaceholderText(_translate("new_unpass", "->不合格项 ->要求值 ->实际值"))
        self.label_8.setText(_translate("new_unpass", "不合格描述"))
        self.label.setText(_translate("new_unpass", "不良品种类"))
        self.label_3.setText(_translate("new_unpass", "批号"))
        self.label_4.setText(_translate("new_unpass", "生产日期"))
        self.label_7.setText(_translate("new_unpass", "数量Kg"))
        self.label_6.setText(_translate("new_unpass", "ID"))
        self.label_2.setText(_translate("new_unpass", "客户"))
        self.label_5.setText(_translate("new_unpass", "不良品名称"))


